/**
 * generated by Xtext 2.18.0
 */
package org.xtext.lab2.layeredStyle.layeredStyleDSL;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.LayeredStyleDSLPackage
 * @generated
 */
public interface LayeredStyleDSLFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LayeredStyleDSLFactory eINSTANCE = org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.LayeredStyleDSLFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Layered Style</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Layered Style</em>'.
   * @generated
   */
  LayeredStyle createLayeredStyle();

  /**
   * Returns a new object of class '<em>Abstract Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abstract Element</em>'.
   * @generated
   */
  AbstractElement createAbstractElement();

  /**
   * Returns a new object of class '<em>Layer</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Layer</em>'.
   * @generated
   */
  Layer createLayer();

  /**
   * Returns a new object of class '<em>Layer Segment</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Layer Segment</em>'.
   * @generated
   */
  LayerSegment createLayerSegment();

  /**
   * Returns a new object of class '<em>Relation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Relation</em>'.
   * @generated
   */
  Relation createRelation();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  LayeredStyleDSLPackage getLayeredStyleDSLPackage();

} //LayeredStyleDSLFactory
