/**
 * generated by Xtext 2.18.0
 */
package org.xtext.lab2.layeredStyle.layeredStyleDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.LayeredStyleDSLFactory
 * @model kind="package"
 * @generated
 */
public interface LayeredStyleDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "layeredStyleDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/lab2/layeredStyle/LayeredStyleDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "layeredStyleDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LayeredStyleDSLPackage eINSTANCE = org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.LayeredStyleDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.LayeredStyleImpl <em>Layered Style</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.LayeredStyleImpl
   * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.LayeredStyleDSLPackageImpl#getLayeredStyle()
   * @generated
   */
  int LAYERED_STYLE = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYERED_STYLE__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Layered Style</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYERED_STYLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.AbstractElementImpl
   * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.LayeredStyleDSLPackageImpl#getAbstractElement()
   * @generated
   */
  int ABSTRACT_ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Abstract Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.LayerImpl <em>Layer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.LayerImpl
   * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.LayeredStyleDSLPackageImpl#getLayer()
   * @generated
   */
  int LAYER = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYER__NAME = ABSTRACT_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Layer Segments</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYER__LAYER_SEGMENTS = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Layer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYER_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.LayerSegmentImpl <em>Layer Segment</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.LayerSegmentImpl
   * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.LayeredStyleDSLPackageImpl#getLayerSegment()
   * @generated
   */
  int LAYER_SEGMENT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYER_SEGMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Layer Segment</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LAYER_SEGMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.RelationImpl <em>Relation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.RelationImpl
   * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.LayeredStyleDSLPackageImpl#getRelation()
   * @generated
   */
  int RELATION = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION__NAME = ABSTRACT_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION__TYPE = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Relation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATION_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.lab2.layeredStyle.layeredStyleDSL.LayeredStyle <em>Layered Style</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Layered Style</em>'.
   * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.LayeredStyle
   * @generated
   */
  EClass getLayeredStyle();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.lab2.layeredStyle.layeredStyleDSL.LayeredStyle#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.LayeredStyle#getElements()
   * @see #getLayeredStyle()
   * @generated
   */
  EReference getLayeredStyle_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.lab2.layeredStyle.layeredStyleDSL.AbstractElement <em>Abstract Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Element</em>'.
   * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.AbstractElement
   * @generated
   */
  EClass getAbstractElement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.lab2.layeredStyle.layeredStyleDSL.AbstractElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.AbstractElement#getName()
   * @see #getAbstractElement()
   * @generated
   */
  EAttribute getAbstractElement_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.lab2.layeredStyle.layeredStyleDSL.Layer <em>Layer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Layer</em>'.
   * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.Layer
   * @generated
   */
  EClass getLayer();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.lab2.layeredStyle.layeredStyleDSL.Layer#getLayerSegments <em>Layer Segments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Layer Segments</em>'.
   * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.Layer#getLayerSegments()
   * @see #getLayer()
   * @generated
   */
  EReference getLayer_LayerSegments();

  /**
   * Returns the meta object for class '{@link org.xtext.lab2.layeredStyle.layeredStyleDSL.LayerSegment <em>Layer Segment</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Layer Segment</em>'.
   * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.LayerSegment
   * @generated
   */
  EClass getLayerSegment();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.lab2.layeredStyle.layeredStyleDSL.LayerSegment#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.LayerSegment#getName()
   * @see #getLayerSegment()
   * @generated
   */
  EAttribute getLayerSegment_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.lab2.layeredStyle.layeredStyleDSL.Relation <em>Relation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relation</em>'.
   * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.Relation
   * @generated
   */
  EClass getRelation();

  /**
   * Returns the meta object for the reference '{@link org.xtext.lab2.layeredStyle.layeredStyleDSL.Relation#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.Relation#getType()
   * @see #getRelation()
   * @generated
   */
  EReference getRelation_Type();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  LayeredStyleDSLFactory getLayeredStyleDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.LayeredStyleImpl <em>Layered Style</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.LayeredStyleImpl
     * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.LayeredStyleDSLPackageImpl#getLayeredStyle()
     * @generated
     */
    EClass LAYERED_STYLE = eINSTANCE.getLayeredStyle();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAYERED_STYLE__ELEMENTS = eINSTANCE.getLayeredStyle_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.AbstractElementImpl
     * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.LayeredStyleDSLPackageImpl#getAbstractElement()
     * @generated
     */
    EClass ABSTRACT_ELEMENT = eINSTANCE.getAbstractElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ABSTRACT_ELEMENT__NAME = eINSTANCE.getAbstractElement_Name();

    /**
     * The meta object literal for the '{@link org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.LayerImpl <em>Layer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.LayerImpl
     * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.LayeredStyleDSLPackageImpl#getLayer()
     * @generated
     */
    EClass LAYER = eINSTANCE.getLayer();

    /**
     * The meta object literal for the '<em><b>Layer Segments</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LAYER__LAYER_SEGMENTS = eINSTANCE.getLayer_LayerSegments();

    /**
     * The meta object literal for the '{@link org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.LayerSegmentImpl <em>Layer Segment</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.LayerSegmentImpl
     * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.LayeredStyleDSLPackageImpl#getLayerSegment()
     * @generated
     */
    EClass LAYER_SEGMENT = eINSTANCE.getLayerSegment();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LAYER_SEGMENT__NAME = eINSTANCE.getLayerSegment_Name();

    /**
     * The meta object literal for the '{@link org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.RelationImpl <em>Relation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.RelationImpl
     * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.impl.LayeredStyleDSLPackageImpl#getRelation()
     * @generated
     */
    EClass RELATION = eINSTANCE.getRelation();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATION__TYPE = eINSTANCE.getRelation_Type();

  }

} //LayeredStyleDSLPackage
