/**
 * generated by Xtext 2.18.0
 */
package org.xtext.lab2.layeredStyle.layeredStyleDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.lab2.layeredStyle.layeredStyleDSL.Relation#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.LayeredStyleDSLPackage#getRelation()
 * @model
 * @generated
 */
public interface Relation extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(Layer)
   * @see org.xtext.lab2.layeredStyle.layeredStyleDSL.LayeredStyleDSLPackage#getRelation_Type()
   * @model
   * @generated
   */
  Layer getType();

  /**
   * Sets the value of the '{@link org.xtext.lab2.layeredStyle.layeredStyleDSL.Relation#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(Layer value);

} // Relation
