/*
 * generated by Xtext 2.18.0
 */
package org.xtext.lab2.layeredStyle.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.lab2.layeredStyleDSL.ui.internal.LayeredStyleDSLActivator;

public class LayeredStyleDSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LayeredStyleDSLActivator.getInstance().getInjector("org.xtext.lab2.layeredStyle.LayeredStyleDSL");
	}

}
