/*
 * generated by Xtext 2.18.0
 */
package org.xtext.lab2.layeredStyle.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LayeredStyleDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/lab2/layeredStyle/parser/antlr/internal/InternalLayeredStyleDSL.tokens");
	}
}
