/*
 * generated by Xtext 2.18.0
 */
package org.xtext.lab2.layeredStyle.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.lab2.layeredStyle.parser.antlr.internal.InternalLayeredStyleDSLParser;
import org.xtext.lab2.layeredStyle.services.LayeredStyleDSLGrammarAccess;

public class LayeredStyleDSLParser extends AbstractAntlrParser {

	@Inject
	private LayeredStyleDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLayeredStyleDSLParser createParser(XtextTokenStream stream) {
		return new InternalLayeredStyleDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "LayeredStyle";
	}

	public LayeredStyleDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LayeredStyleDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
