/*
 * generated by Xtext 2.18.0
 */
package org.xtext.lab2.layeredStyle.ide


/**
 * Use this class to register ide components.
 */
class LayeredStyleDSLIdeModule extends AbstractLayeredStyleDSLIdeModule {
}
