/**
 * generated by Xtext 2.18.0
 */
package org.xtext.lab2.layeredStyle.validation;

import org.xtext.lab2.layeredStyle.validation.AbstractLayeredStyleDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class LayeredStyleDSLValidator extends AbstractLayeredStyleDSLValidator {
}
