/*
 * generated by Xtext 2.18.0
 */
package org.xtext.lab2.layeredStyle.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.lab2.layeredStyleDSL.ui.internal.LayeredStyleDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LayeredStyleDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(LayeredStyleDSLActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		LayeredStyleDSLActivator activator = LayeredStyleDSLActivator.getInstance();
		return activator != null ? activator.getInjector(LayeredStyleDSLActivator.ORG_XTEXT_LAB2_LAYEREDSTYLE_LAYEREDSTYLEDSL) : null;
	}

}
