/*
 * generated by Xtext 2.18.0
 */
package org.xtext.lab2.layeredStyle.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class LayeredStyleDSLProposalProvider extends AbstractLayeredStyleDSLProposalProvider {
}
