/**
 * generated by Xtext 2.18.0
 */
package org.xtext.lab2.layeredStyle.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class LayeredStyleDSLQuickfixProvider extends DefaultQuickfixProvider {
}
