/**
 * generated by Xtext 2.18.0
 */
package org.xtext.lab2.layeredStyle.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.lab2.layeredStyle.ui.AbstractLayeredStyleDSLUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class LayeredStyleDSLUiModule extends AbstractLayeredStyleDSLUiModule {
  public LayeredStyleDSLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
