/**
 * generated by Xtext 2.18.0
 */
package org.xtext.lab2.layeredStyle.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.lab2.layeredStyle.LayeredStyleDSLRuntimeModule;
import org.xtext.lab2.layeredStyle.LayeredStyleDSLStandaloneSetup;
import org.xtext.lab2.layeredStyle.ide.LayeredStyleDSLIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class LayeredStyleDSLIdeSetup extends LayeredStyleDSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    LayeredStyleDSLRuntimeModule _layeredStyleDSLRuntimeModule = new LayeredStyleDSLRuntimeModule();
    LayeredStyleDSLIdeModule _layeredStyleDSLIdeModule = new LayeredStyleDSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_layeredStyleDSLRuntimeModule, _layeredStyleDSLIdeModule));
  }
}
