/**
 * generated by Xtext 2.18.0
 */
package org.xtext.lab2.layeredStyle.ide;

import org.xtext.lab2.layeredStyle.ide.AbstractLayeredStyleDSLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class LayeredStyleDSLIdeModule extends AbstractLayeredStyleDSLIdeModule {
}
