/**
 * generated by Xtext 2.18.0
 */
package org.xtext.lab2.layeredStyle.ui.contentassist;

import org.xtext.lab2.layeredStyle.ui.contentassist.AbstractLayeredStyleDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class LayeredStyleDSLProposalProvider extends AbstractLayeredStyleDSLProposalProvider {
}
