/*
 * generated by Xtext 2.18.0
 */
package org.xtext.lab2.layeredStyle


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class LayeredStyleDSLStandaloneSetup extends LayeredStyleDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new LayeredStyleDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
