/**
 * generated by Xtext 2.18.0
 */
package org.xtext.lab2.layeredStyle;

import org.xtext.lab2.layeredStyle.AbstractLayeredStyleDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class LayeredStyleDSLRuntimeModule extends AbstractLayeredStyleDSLRuntimeModule {
}
