/**
 * generated by Xtext 2.18.0
 */
package org.xtext.lab2.layeredStyle;

import org.xtext.lab2.layeredStyle.LayeredStyleDSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class LayeredStyleDSLStandaloneSetup extends LayeredStyleDSLStandaloneSetupGenerated {
  public static void doSetup() {
    new LayeredStyleDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
