/**
 * generated by Xtext 2.18.0
 */
package org.xtext.lab2.layeredStyle.layeredStyleDSL.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.lab2.layeredStyle.layeredStyleDSL.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class LayeredStyleDSLFactoryImpl extends EFactoryImpl implements LayeredStyleDSLFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static LayeredStyleDSLFactory init()
  {
    try
    {
      LayeredStyleDSLFactory theLayeredStyleDSLFactory = (LayeredStyleDSLFactory)EPackage.Registry.INSTANCE.getEFactory(LayeredStyleDSLPackage.eNS_URI);
      if (theLayeredStyleDSLFactory != null)
      {
        return theLayeredStyleDSLFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new LayeredStyleDSLFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LayeredStyleDSLFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case LayeredStyleDSLPackage.LAYERED_STYLE: return createLayeredStyle();
      case LayeredStyleDSLPackage.ABSTRACT_ELEMENT: return createAbstractElement();
      case LayeredStyleDSLPackage.LAYER: return createLayer();
      case LayeredStyleDSLPackage.LAYER_SEGMENT: return createLayerSegment();
      case LayeredStyleDSLPackage.RELATION: return createRelation();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LayeredStyle createLayeredStyle()
  {
    LayeredStyleImpl layeredStyle = new LayeredStyleImpl();
    return layeredStyle;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AbstractElement createAbstractElement()
  {
    AbstractElementImpl abstractElement = new AbstractElementImpl();
    return abstractElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Layer createLayer()
  {
    LayerImpl layer = new LayerImpl();
    return layer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LayerSegment createLayerSegment()
  {
    LayerSegmentImpl layerSegment = new LayerSegmentImpl();
    return layerSegment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Relation createRelation()
  {
    RelationImpl relation = new RelationImpl();
    return relation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LayeredStyleDSLPackage getLayeredStyleDSLPackage()
  {
    return (LayeredStyleDSLPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static LayeredStyleDSLPackage getPackage()
  {
    return LayeredStyleDSLPackage.eINSTANCE;
  }

} //LayeredStyleDSLFactoryImpl
