/*
 * generated by Xtext 2.18.0
 */
package org.xtext.lab2.layeredStyle.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLayeredStyleDSLScopeProvider extends DelegatingScopeProvider {
}
